### ISSUE TITLE
Sync Metadata error

### ISSUE THREAD

**Issue by Singgoli** [microsoft/FabricBQSync#84]
I found out i got an error when i try to do sync metadata for the first time after installing.
Can you help me find out what caused the error? I am relatively new to GCP and Spark

below is the error message i got.
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/unique-well-442507-t9/jobs?prettyPrint=false
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "Syntax error: Expected end of input but got \"-\" at [2:42]",
      "reason": "invalidQuery"
    }
  ],
  "message": "Syntax error: Expected end of input but got \"-\" at [2:42]",
  "status": "INVALID_ARGUMENT"
}

**Comment by bluewatersql** [comment]
Issue was invalid BQ query. Closing.
